// Code generated by "stringer -type=OperativeMode"; DO NOT EDIT.

package system

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Manual-0]
	_ = x[Automatic-1]
}

const _OperativeMode_name = "ManualAutomatic"

var _OperativeMode_index = [...]uint8{0, 6, 15}

func (i OperativeMode) String() string {
	if i < 0 || i >= OperativeMode(len(_OperativeMode_index)-1) {
		return "OperativeMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperativeMode_name[_OperativeMode_index[i]:_OperativeMode_index[i+1]]
}
